data: "./data/bigger_training_data.parquet"
# data: "./data/test_data.parquet"

training_params:
  learning_rate: 0.0001
  batch_size: 256
  max_epochs: 7
  num_workers: 0
  log_every_n: 1
  accumulate_grad_batches: 4
  p_mask: 0.2
  mask_tokens: True
  holdout_prob: .1

net_params:
  d_model: 256
  sequence_length: 128
  n_layers: 4
  n_head: 4
  dim_ff: 256
  dropout: 0.2

features:
  release_speed: numeric
  pfx_x: numeric
  pfx_z: numeric
  n_batters_faced: numeric
  stand: categorical
  zone: categorical
  pitcher: categorical
  batter: categorical
  pitch_type: categorical
  description: categorical
  events: categorical
